### ISSUE TITLE
[Normal] Program Test Check Lists

### ISSUE THREAD

**Issue by kimch0612** [kimch0612/OOP2_Project#14]
## Summary
- 프로그램이 정상적으로 작동하는지 테스트할 때 사용할 체크 리스트입니다.

## Description
- 하단에 작성된 표를 기준으로 테스트하되, 그 결과를 이 Issues의 Comment란에 작성합니다. 
이때, Result가 KO인 경우 KO Reason을 하단에 함께 작성합니다. (추측성도 괜찮음)

```
| Category | Content |
|:---|:---|
| OS |  테스트한 운영체제의 자세한 정보를 기입합니다. winver 명령어를 통해 확인할 수 있습니다. |
| Architecture | 시스템 종류를 기입합니다. 32Bit, 64Bit, ARM등이 있습니다. |
| RAM | RAM 용량을 기입합니다. |
| Disc Space | 디스크의 남은 용량을 기입합니다. |
| Resolution | 해상도를 기입합니다. |
| Magnifier | 디스플레이의 배율을 기입합니다. |
| Result | 프로그램 구동 결과를 OK / KO로 기입합니다. |
| KO Reason | 예상되는 프로그램 구동이 실패한 이유를 기입합니다. |
```

**Comment by kimch0612** [comment]
- 아래의 표는 위의 양식을 바탕으로 작성한 예시입니다.

| Category | Content |
|:---|:---|
| OS | Windows 11 Pro 23H2 22631.2428 |
| Architecture | 64Bit |
| RAM | 16GB |
| Disc Space | 512GB |
| Resolution | 1920x1080 |
| Magnifier | 125% |
| Result | OK |
| KO Reason | - |

**Comment by kimch0612** [comment]
| Category | Content |
|:---|:---|
| OS | Windows 10 Home 21H2 19044 |
| Architecture | 32Bit |
| RAM | 8GB |
| Disc Space | 256GB |
| Resolution | 1920x1080 |
| Magnifier | 200% |
| Result | KO |
| KO Reason | Magnifier가 너무 높아서? |

**Comment by SevensSta** [comment]
| Category | Content |
|:---|:---|
| OS |  Windows10 22H2 19045.2965 |
| Architecture | 64bit |
| RAM | 8GB |
| Disc Space | 197GB |
| Resolution | 1280x1024 |
| Magnifier | 100% |
| Result | OK |
| KO Reason | - |

**Comment by SevensSta** [comment]
| Category | Content |
|:---|:---|
| OS | window 10 22H2 19045, 3693   |
| Architecture | 64bit |
| RAM | 16GB |
| Disc Space | 71.3GB |
| Resolution | 1920x1080 |
| Magnifier | 125% |
| Result | OK |
| KO Reason | - |

**Comment by kimch0612** [comment]
| Category | Content |
|:---|:---|
| OS |  Windows XP Professional K v5.1.2600 |
| Architecture | 32Bit |
| RAM | 2GB |
| Disc Space | 29.4GB |
| Resolution | 1280x720 |
| Magnifier | 100% |
| Result | KO |
| KO Reason | OS 버전이 너무 낮은 듯. |

![test_110124](https://github.com/kimch0612/OOP2_Project/assets/10193967/b23db3c5-9ef1-42b1-8552-635e3d2e0225)

**Comment by kimch0612** [comment]
| Category | Content |
|:---|:---|
| OS |  Windows Vista Home Premium K v6.0.6002 |
| Architecture | 32Bit |
| RAM | 2GB |
| Disc Space | 22.7GB |
| Resolution | 1280x720 |
| Magnifier | 100% |
| Result | KO |
| KO Reason | OS 버전이 너무 낮은 듯. |

![test_112818](https://github.com/kimch0612/OOP2_Project/assets/10193967/4673a161-491c-4261-91ee-b0af31252abf)

**Comment by kimch0612** [comment]
| Category | Content |
|:---|:---|
| OS |  Windows 7 Ultimate K v6.1.7601 |
| Architecture | 32Bit |
| RAM | 2GB |
| Disc Space | 21GB |
| Resolution | 1280x720 |
| Magnifier | 100% |
| Result | KO |
| KO Reason | 32Bit OS에선 구동이 불가능한 듯 |

![test_114412](https://github.com/kimch0612/OOP2_Project/assets/10193967/8a5a5f16-e4de-4e0f-b7c3-99484a25b930)

**Comment by kimch0612** [comment]
| Category | Content |
|:---|:---|
| OS |  Windows 7 Ultimate K v6.1.7601 |
| Architecture | 64Bit |
| RAM | 2GB |
| Disc Space | 29GB |
| Resolution | 1280x720 |
| Magnifier | 100% |
| Result | KO |
| KO Reason | 특정 DLL이 부족하다하여 넣어줘봤는데 여전히 실행 불가능. 좀 더 알아봐야 할 듯. |

![test_125128](https://github.com/kimch0612/OOP2_Project/assets/10193967/7676552f-6afa-411c-9f29-c9f536dee74b)
![test_125720](https://github.com/kimch0612/OOP2_Project/assets/10193967/482a646a-d0e4-475f-900d-9851136cf7a1)

**Comment by kimch0612** [comment]
| Category | Content |
|:---|:---|
| OS |  Windows 8.1 v6.3.9600 |
| Architecture | 64Bit |
| RAM | 4GB |
| Disc Space | 24GB |
| Resolution | 1920x1080 |
| Magnifier | 100% |
| Result | KO |
| KO Reason | 8.1에서도 역시 구동이 안 됐음 |

![test_131545](https://github.com/kimch0612/OOP2_Project/assets/10193967/f4986b5e-a902-4a2f-99bf-11804f9b08d2)

**Comment by kimch0612** [comment]
| Category | Content |
|:---|:---|
| OS |  Windows 11 20H2 19042.610 |
| Architecture | 64Bit |
| RAM | 4GB |
| Disc Space | 120GB |
| Resolution | 1280x720 |
| Magnifier | 100% |
| Result | OK |
| KO Reason | - |

![DeDRM Env_132022](https://github.com/kimch0612/OOP2_Project/assets/10193967/86b90bd4-f10d-4ef0-b6e9-c2a36f47fabc)

**Comment by SeoJin0513** [comment]
| Category | Content |
|:---|:---|
| OS |  Windows 11  23H2 22631.2715  |
| Architecture |64bit  |
| RAM | 16GB |
| Disc Space | 500GB |
| Resolution |3440 X 1440  |
| Magnifier | 100%. |
| Result | OK |
| KO Reason | - |

**Comment by SeoJin0513** [comment]
| Category | Content |
|:---|:---|
| OS |  Windows 11  23H2 22631.2715  |
| Architecture |64bit  |
| RAM | 16GB |
| Disc Space | 500GB |
| Resolution |3840 X 2160  |
| Magnifier | 100% |
| Result | OK |
| KO Reason | - |

**Comment by SeoJin0513** [comment]
| Category | Content |
|:---|:---|
| OS |  Windows 11  23H2 22631.2715  |
| Architecture |64bit  |
| RAM | 16GB |
| Disc Space | 500GB |
| Resolution |1152 X 864  |
| Magnifier | 100%. |
| Result | OK |
| KO Reason | - |

**Comment by SeoJin0513** [comment]
| Category | Content |
|:---|:---|
| OS |  Windows 11  23H2 22631.2715  |
| Architecture |64bit  |
| RAM | 16GB |
| Disc Space | 500GB |
| Resolution |1024 X 768  |
| Magnifier | 100%. |
| Result | OK |
| KO Reason | - |

**Comment by SeoJin0513** [comment]
| Category | Content |
|:---|:---|
| OS |  Windows 11  23H2 22631.2715  |
| Architecture |64bit  |
| RAM | 16GB |
| Disc Space | 500GB |
| Resolution |800 X 600  |
| Magnifier | 100%. |
| Result | KO |
| KO Reason | 실행은 문제가 없으나 해상도에 게임화면 전체를 담지못하는 이슈 |

**Comment by kimch0612** [comment]
| Category | Content |
|:---|:---|
| OS |  Windows 11 23H2 22631.2715 |
| Architecture | 64Bit |
| RAM | 16GB |
| Disc Space | 500GB |
| Resolution | 2560x1440 |
| Magnifier | 125% |
| Result | OK |
| KO Reason | - |

![image](https://github.com/kimch0612/OOP2_Project/assets/10193967/34bfef44-e272-4025-8d66-aa09ce8f3f05)

**Comment by SevensSta** [comment]
| Category | Content |
| OS | window 10 22H2 19045.3693|
| Architecture | 64bit |
| RAM | 16GB |
| Disc Space | 297MB |
| Resolution | 1920x1080 |
| Magnifier | 125% |
| Result | OK |
| KO Reason | - |

**Comment by SevensSta** [comment]
| Category | Content |
|:---|:---|
| OS | window 10 22H2 19045.3693|
| Architecture | 64bit |
| RAM | 16GB |
| Disc Space | 297MB |
| Resolution | 1920x1080 |
| Magnifier | 125% |
| Result | OK |
| KO Reason | - |

**Comment by SevensSta** [comment]
| Category | Content |
|:---|:---|
| OS | window 10 22H2 19045.3693|
| Architecture | 64bit |
| RAM | 16GB |
| Disc Space | 297MB |
| Resolution | 1920x1080 |
| Magnifier | 150% |
| Result | OK |
| KO Reason | - |

**Comment by SevensSta** [comment]
| Category | Content |
|:---|:---|
| OS | window 10 22H2 19045.3693|
| Architecture | 64bit |
| RAM | 16GB |
| Disc Space | 297MB |
| Resolution | 1920x1080 |
| Magnifier | 175% |
| Result | OK |
| KO Reason | - |

**Comment by SevensSta** [comment]
| Category | Content |
|:---|:---|
| OS | window 10 22H2 19045.3693|
| Architecture | 64bit |
| RAM | 16GB |
| Disc Space | 297MB |
| Resolution | 1920x1080 |
| Magnifier | 125% |
| Result | KO |
| KO Reason | 프로그램 구동은 잘되지만 화면에 다 담을 수없음 |

**Comment by SevensSta** [comment]
| Category | Content |
|:---|:---|
| OS | window 10 22H2 19045.3693|
| Architecture | 64bit |
| RAM | 16GB |
| Disc Space | 387MB |
| Resolution | 1024x768 |
| Magnifier | 100% |
| Result | OK |
| KO Reason | - |

**Comment by kanghyeongwon5672** [comment]
| Category | Content |
|:---|:---|
| OS |  window 10 21H2 19044.3086
| Architecture | 64bit
| RAM | 16GB
| Disc Space | 99.5GB
| Resolution | 1920x1080
| Magnifier | 100%
| Result | OK
| KO Reason |

**Comment by kanghyeongwon5672** [comment]
| Category | Content |
|:---|:---|
| OS |  window 10 21H2 19044.3086
| Architecture | 64bit
| RAM | 16GB
| Disc Space | 99.5GB
| Resolution | 1920x1080
| Magnifier | 150%
| Result | OK
| KO Reason |

**Comment by kanghyeongwon5672** [comment]
| Category | Content |
|:---|:---|
| OS |  window 10 21H2 19044.3086
| Architecture | 64bit
| RAM | 16GB
| Disc Space | 99.5GB
| Resolution | 1920x1080
| Magnifier | 175%
| Result | OK
| KO Reason |

**Comment by kanghyeongwon5672** [comment]
| Category | Content |
|:---|:---|
| OS |  window 10 21H2 19044.3086
| Architecture | 64bit
| RAM | 16GB
| Disc Space | 99.5GB
| Resolution | 800x600
| Magnifier | 100%
| Result | OK
| KO Reason |

**Comment by kanghyeongwon5672** [comment]
| Category | Content |
|:---|:---|
| OS |  window 10 21H2 19044.3086
| Architecture | 64bit
| RAM | 16GB
| Disc Space | 24.2GB
| Resolution | 800x600
| Magnifier | 100%
| Result | OK
| KO Reason |

**Comment by kanghyeongwon5672** [comment]
| Category | Content |
|:---|:---|
| OS |  window 10 21H2 19044.3086
| Architecture | 64bit
| RAM | 16GB
| Disc Space | 24.2GB
| Resolution | 1280x720
| Magnifier | 100%
| Result | OK
| KO Reason |

**Comment by Trevorjun** [comment]
| Category | Content |
|:---|:---|
| OS |  Windows 10 22H2 19045.3693 |
| Architecture | 64bit |
| RAM | 8GB |
| Disc Space | 43.6GB|
| Resolution | 1920x1080 |
| Magnifier | 125% |
| Result | OK |
| KO Reason | - |

**Comment by Trevorjun** [comment]
| Category | Content |
|:---|:---|
| OS |  Windows 10 22H2 19045.3693 |
| Architecture | 64bit |
| RAM | 8GB |
| Disc Space | 43.6GB|
| Resolution | 1920x1080 |
| Magnifier | 175% |
| Result | OK |
| KO Reason | - |

**Comment by Trevorjun** [comment]
| Category | Content |
|:---|:---|
| OS |  Windows 10 22H2 19045.3693 |
| Architecture | 64bit |
| RAM | 8GB |
| Disc Space | 43.6GB|
| Resolution | 1400x1050 |
| Magnifier | 125% |
| Result | OK |
| KO Reason | - |

**Comment by Trevorjun** [comment]
| Category | Content |
|:---|:---|
| OS |  Windows 10 22H2 19045.3693 |
| Architecture | 64bit |
| RAM | 8GB |
| Disc Space | 43.6GB|
| Resolution | 1152x864 |
| Magnifier | 125% |
| Result | OK |
| KO Reason | - |

**Comment by Trevorjun** [comment]
| Category | Content |
|:---|:---|
| OS |  Windows 10 22H2 19045.3693 |
| Architecture | 64bit |
| RAM | 8GB |
| Disc Space | 39.6GB|
| Resolution | 1360x768 |
| Magnifier | 100% |
| Result | OK |
| KO Reason | - |
